language: ruby
rvm:
- 2.5
env:
  global:
  - CC_TEST_REPORTER_ID=18fcb1674448a0f6f36c0b849ca7bb1f7e9c1fa72688fce866e1add6044cd073
  - secure: bR7hyzL3kyAYAXluyPV9D1GmqwLLLUdOt3P5grYG61GeekVKJ52BIDdDYjGzr4PWVKrLrLSOIrP1Luy8GjvOcaTHIu3dVE0HsWrtcaUh04STMsyH0NEJm7ePG7bPJAiWzZ1vA/okaCJ0vBmG5RrID4gLQx//nGR9TkBctuQLb0wxpFEpKxW2INXNKqfsKhz9jYP227x1BtrtU2SgcLtRaqzcTDAEsgkG0YOaL73AuK8hye5o1rEEDJ4KErVe4d+jSPMrV+AEWYxX7GrbMVocN7YzP2iQ6Cmzf+HGkH+4TaB877x/eDm9Co/LenaNswRVV3o8vF77Euj3PYWQOl6qBbnelR/KpdCpYemDaR8SgACM6gw26tUo9zAVyZ3U3bxfbWwzD+N/mcX2xZtxkFEBRhYSc/kKxlxGOyxLEFtC2TL5Icf0t84B7Ai8EakVxQJ2ubMPQv0QKJREYPWN8gEq7nsuyJ2+1FZC9hzxv3/yIsmNfSCs4LZviLiMpq+mNLOaYU1ZDsZ3AnXYC+fiGm4IXj7pBSKzpBYw1Qbu/Tba/vu+GiL1F7FGfg61nTZkGWT/0IPT820QlwRkVksn5R1R5EufJwxKAnWfmEnBlG93PbUJE6ZpZt+prvXh7bK68jjy51wxgIhlqKnaT8Zop/A7+knU/9Aa3DRUXLfhmCu0ktQ=
  - secure: b2ZKVbjDt4Qu6jmhYs8hSdg5PquctEBKK1poIi4FpqdSMFZ9xjERVVMnQBDSHPa+biN/JDNzyhYppt404GfftYvP91drxwAEivNeDmFh2m0AoaH+M8AqnniLTp8UavK2LqSmq/8MTbWG7HXpME2w9cVekcquVwpVW9KSs9d7HE/QVSDFTYxn5s0YYqSBPU9217TG08oXPFQE7w7N98cOoQVfq4DKQDN1VwprmbuGRfclxNNn+FmmnPgliX0GJTIEld1mC3qQY7BRIQHzjcCdXLUzJFjx0PLvPS8tj6qeBOC32z62ayCzhsiMlJS6YqEErnNWj60FabhSfKKFHr8tnHmEpx0M+sTsNK6mh+uK+EE4pTH8sS/kS7mWs1bhBHXMih7kLwerS3syQRzz3G/+aARcq6DEnFVcOpCzeEgNqFa1zs+0VLbcJ1ssJsEPtWgQ8Cgn5sDWzyQB6uHdsjnlXF53fQBtT4EbhhbHDwSjECVr00KrmP9ElSsccq6mc6aLB/z/LGyauskStkAAw1s5jvAccc/MPapcCvPGuHHjjOcqvAaAIHjXw3mvcGzd2KlrZ8FbPYK50KskpI8WVs1e98sr22IDJ2MiHSpbe7AQbClTsw+Kci91zNbFD7n97lkCradR7DAgg0lATbVCRWcLbZ31v80uEFxyTrnlZoAMLiI=
  - secure: zYxh8SG5B+l7SLGK++Xz9diiraU9IrMl2x6/YzorjoI/0DO9DrS/oV2XwSxk8tPSaHNhnyMIn+gFN7HAgE6IXINkH9rEg4bK8z1RkYZ+U0JwcuTHclIpGi8ZZFZ3UHtRvzHYTBRX/E74I/ugTrZbVeRZ8JPjj/+v28d3YVa0l6IjWLjVFFYzzPduEuOdBSKkPX8EYwTnexNB22YFZKPj9FX8ZrqhdLqiI40jKjjV5KBwtMknWisIe/BTCKIknwMfQjnysy79lEAqZs68PGo8XWA2/60XPYe4ThOJUPEk/JzglJ48WnEs9sSEmpXeox+8rB+I7OYUXu3uZ4ChIk1cq/EpYav48LQBgsBeRI1CPFsVXSnNJN/6Gnhn4ZsOWrFrGTW1ZDq6NcPPXXUdsDtvgUZUDQYRP0MOnUTNZs57x43jsHGAk5AbUUggomlWa+EbP7iBMlkmrlYBJwz+ILP7A9dhW9AfSG3iAH1J5CnODbb23rbJcovkdSdWdGI1z4l32wj3ndjz3dGqP8eXVz2bfFoGzbCPfVzinttsKZKwxUDHoDrnJekC38NHO1Roq+axBPxKlT0OGpc99ae3cda12khLMAmZUY4G4ZbU0RTqCWu/KPrTKBIRJNOnNiaLxl+IZqDkEvaeS1bLS1bphs1+2KwkXjhaoyBD/V5kXxPNuOU=
services:
- postgresql
before_script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle
- bundle exec rspec
- bundle exec rubocop
branches:
  only:
  - master
after_script:
- "./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: rkFL1f9nHhXQsrn8sO3ll6Y3DFXaSsnrk2bLpPcNC2f6nOV5HyxGaKch8nv3b2hcxz6QKpAU2c4mmTUVyqVxGtTwUZdeBqrVo10OZLQIYjgFZVRmRPeA8eNPBFc4kDPVsSWpgl/+M3vKXEUVJOVdE2hwSp7MafBWzB8qFCO6RqUKTJt9YpoLTsLJpGFCkEUbGZJ1XEUJRacoxUl8IsMCP3lGxER4vC0LgsxOWSkKR40MRU8xKG9B8eoewixZmyGtnW4tNuHTNPNk0jG2QcCuY7a7XAZfTezJ4Eee6mfNf6Sifozgi/Cy92SHPlxtUyRvFDRrJs0lPoO/ZoJhWsfCjR04VsLTvwbILWDsg/f4Cu0070B2Sk6/WTDqC4aZCechLc5jHpCdQfs4j8UIOTGJKkALQiVM6QbAMe02OvgsQiMs2KOykFjKWBqPgJgsYMKV/edt1NSIX1Bj+SUsbkEdrzpyD2JbdakxgysmzOz8xuCGnEZ7CLGBP+Tap5HIlb7MGwE+Hiutw12Apeynzdgh2X/GIw0YBc4P2xJf1WQ4hOs2jbUMltv9jqoJJehAa3E6AZgqIWxIicDP0cXYTu2sJnTjUP73TFPjWTORj18y/VfaFZhiJFMQPlfFBt5tmi+OfLCOeEg04Hp9IHNRiJELm3tkpXFdw8rX3zIVbb058Uc=
  app: acebook-pingpong
  on:
    repo: Peter2-71828/aceBook-PingPong
